# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Assets

on:
  push:
    branches:
      - "master"
      - "deploy"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: mkdir "$HOME/.ssh" && touch "$HOME/.ssh/id_rsa"
      - run: yarn --force
      - run: yarn build
      - run: zip -r dist.zip dist/*
      - name: Get short SHA
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.sha_short.outputs.sha_short }}
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.webhook_url }}
          webhook_secret: ${{ secrets.webhook_secret }}
          webhook_auth: "deploy:${{ secrets.webhook_code }}"
